# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
# version: 2.1
# orbs: 
#   cypress: cypress-io/cypress@2.0.0

# workflows:
#   build: 
#     jobs:
#     - cypress/run:
#       start: npm start
#       wait-on: 'http://localhost:3000'

version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/run:
          start: npm start
          wait-on: 'http://localhost:4200'


